### ISSUE TITLE
Fonts not downloading and loading

### ISSUE THREAD

**Issue by ouun** [kirki-framework/field-typography#2]
@aristath thank you very much for the amazing work and the very fast response times... Impressive!

Not sure whether you prefer 4.0 related issues and PRs here or on aristath/kiri? I have the feeling that you can keep a better overview here as the controls and modules are separated.

However I started to do some tests with the 4.0 packages and it is very promising. I'm - of cause - facing a bunch of issues. Especially at the usage of the Typography field, where I got a couple of questions:

1.) Lets say I do not need/want 3.x API support. Do I still need to require `"kirki-framework/compatibility"`? Asking because it seems to be required by some Modules such as `"kirki-framework/module-webfonts"` `"kirki-framework/module-css"` & `"kirki-framework/module-postmessage"`.

2.) Is it the correct approach for 4.0 to just require the composer packages I want to use and to init them via a regular Class call such as:

```
new Kirki\Module\CSS();
new Kirki\Module\Postmessage();
new Kirki\Module\Webfonts();
```
For me PSR-4 is autoloading all above classes correctly, however in some cases I get Postmessage working correctly but I never got Webfonts downloading the fonts and CSS loading it correctly in the frontend. Wondering if I am too early for testing this or missing something.

Thanks!

**Comment by ouun** [comment]
Going a bit deeper into this I recognized that `Kirki::$fields` is always empty. So it seems that the subfields for "Typography" are not added to the global variable and that causes the function `Webfonts\loop_fields()` to use an empty array `Kirki::$fields`. 
Adding the `CSS::$fields` array for testing fixes the above mentioned issue and Kirki downloads the fonts and loads them in frontend.

**Comment by aristath** [comment]
> @aristath thank you very much for the amazing work and the very fast response times... Impressive!

Thank you! Actually the "fast times" only apply during the weekends. On weekdays I'm not as active and people have to wait a bit more 😆 

> Not sure whether you prefer 4.0 related issues and PRs here or on aristath/kiri? I have the feeling that you can keep a better overview here as the controls and modules are separated.

PRs and issues in the packages are preferable to issues/PRs in the main Kirki plugin. It's still a WIP structure so most tickets come in the main kirki repo, I'm hoping that will change once v4.0 is stable and people start using the composer packages.

> 1.) Lets say I do not need/want 3.x API support. Do I still need to require `"kirki-framework/compatibility"`? Asking because it seems to be required by some Modules such as `"kirki-framework/module-webfonts"` `"kirki-framework/module-css"` & `"kirki-framework/module-postmessage"`.

No, you shouldn't have to. Right now I haven't dealt with the dependencies of each package, I wanted to first of all make the main plugin work with the new APIs before I start cleaning up some things, properly define dependencies and so on. Most of them won't be needed, but I haven't had the time to test all cases/packages separately to see what each one needs to run 100% independently.
It's still a work in progress and all these things will be done prior to the official 4.0 release. 👍 

> 2.) Is it the correct approach for 4.0 to just require the composer packages I want to use and to init them via a regular Class call such as:
> 
> ```
> new Kirki\Module\CSS();
> new Kirki\Module\Postmessage();
> new Kirki\Module\Webfonts();
> ```
> For me PSR-4 is autoloading all above classes correctly, however in some cases I get Postmessage working correctly but I never got Webfonts downloading the fonts and CSS loading it correctly in the frontend. Wondering if I am too early for testing this or missing something.

You're not doing it wrong. I'm still figuring out some details for the new API. For example:
To create a new color control in v4.0 you'd do something like this:
```php
new \Kirki\Field\Color( [
	'option_type' => 'theme_mod',
	'capability'  => 'edit_theme_options',
	'default'     => '#fff',
	'transport'   => 'refresh', // Or postMessage.
	'label'       => esc_html__( 'My Color Control', 'theme_textdomain' ),
	'section'     => 'colors',
	'choices'     => [
		'alpha' => true,
	]
] );
```
The [`\Kirki\Field\Color`](https://github.com/kirki-framework/control-color/blob/master/src/Field/Color.php) object extends [`\Kirki\Field`](https://github.com/kirki-framework/field/blob/master/src/Field.php), and in there you can find the main filters & actions that the new implementation for most modules use.
Now, in the [`CSS`](https://github.com/kirki-framework/module-css/blob/bd540f609f82eb1354846a26ad24ac81ee50fb10/src/CSS.php) module for example, you'll see this line in its constructor:
```php
add_action( 'kirki_field_init', [ $this, 'field_init' ], 10, 2 );
```
If you examine the `field_init` method, you'll see that it takes care of fields added with the new API, since new fields use the `kirki_field_init` hook.
Fields added via the old APIs can be found in `Kirki::$fields`, and that's why on that same file you'll see a loop running on that. This is also the reason why you see lots of modules still require the `compatibility` package... I have not yet managed to completely separate everything because I want to be real careful with backwards compatibility.

> Going a bit deeper into this I recognized that Kirki::$fields is always empty. So it seems that the subfields for "Typography" are not added to the global variable and that causes the function Webfonts\loop_fields() to use an empty array Kirki::$fields.

As mentioned above, `Kirki::$fields` is only used for backwards compatibility.

> Adding the CSS::$fields array for testing fixes the above mentioned issue and Kirki downloads the fonts and loads them in frontend.

Then that's definitely a bug, I probably haven't migrated the structure of that package to the new APIs yet - or missed a hook somewhere.

**Comment by ouun** [comment]
Wow, again thanks for the fast and detailed reply.
Anyway, the above was was too early. I did not recognize that some fields can bypass this when they are not registered with `Kirki::add_field()` such as the typography subfields. I guess you'll have a better/correct place to add them to `Kirki::$fields`. So I'll stop investigating this one. But in general it would be fantastic to fix the bug which keeps `Kirki::$fields` empty.
So far it makes absolutely sense to do it in `Kirki/Field` and I guess that something similiar to...
````
add_action( 'kirki_field_init', [ $this, 'field_init' ], 10, 2 );
````
... needs to be done in Webfonts. If that is correct and you don't mind, I'll be happy to have a look to it. 

Your approach for 4.0 makes totally sense and as I just start to get some controls implemented into my project I'm fine to support a bit the further development.

**Comment by aristath** [comment]
Yes, that is correct. A hook on `kirki_field_init` should be added in the `Webfonts` class.
Of course I don't mind you taking a look, sumbitting PRs etc, I welcome those things! This project is sometimes too big for a single person, and one of the reasons for splitting it to separate packages was to make it easier for people to contribute! 👍

**Comment by ouun** [comment]
Thanks @aristath. I added a PR to the `Webfonts` module (https://github.com/kirki-framework/module-webfonts/pull/1) and will close this one. Lets see where I can provide some contribution.
